### ISSUE TITLE
Image Hover, Image Expansion Sync

### ISSUE THREAD

**Issue by randoomdude** [dnsev/iex#1]
Sounds are enabled and it works great with latest version but whenever you want to switch from image hover to expanded image the audio starts over again, do you know if you can set it up so that the time stamp on the video stays the same whether its hovered or expanded?

**Comment by dnsev** [comment]
Might give it a shot; hopefully it won't be too big of an issue since image expansion isn't done using this extension, but the 4chan native/4chan-x extension, whichever you may use.

**Comment by dnsev** [comment]
Should be changed if you update to [2.7.2](https://dnsev.github.io/iex/#!changes)

**Comment by randoomdude** [comment]
it's beautiful, thank you

**Comment by randoomdude** [comment]
do you know if the reverse is possible? having an expanded image that has already begun playing and closing it and switching to hover picking up where it left off?

**Comment by dnsev** [comment]
Should be updated in [2.8](https://dnsev.github.io/iex/#!changes).

May be buggy at times due to it being hard to interface with the other 4chan scripts running, but it seemed to work alright in testing.
